MODEL:
  ARCH: Hendrycks2020AugMix_ResNeXt
  CLASSIFIER_NAME: 'classifier'
DATA_FITER:
  CONFIDENCE_FACTOR: 0.66
  ENTROPY_FACTOR: 0.30
CORRUPTION:
  DATASET: cifar100
  NUM_CLASS: 100
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise