MODEL:
  ARCH: Standard
  CLASSIFIER_NAME: 'fc'
DATA_FITER:
  CONFIDENCE_FACTOR: 0.99
  ENTROPY_FACTOR: 0.15

  # Consistent filter
  CONSISTENT_LAMBDA_STD: 1.0
  CONSISTENT_HARD_FLOOR: 0.6
CORRUPTION:
  DATASET: cifar10
  NUM_CLASS: 10
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise